### ISSUE TITLE
Can't run Waze DAG locally using docker-compose

### ISSUE THREAD

**Issue by carmelp16** [hasadna/anyway-etl#14]
## Steps to reproduce:

- Clone [my fork](https://github.com/carmelp16/anyway-etl) and checkout to `feature/waze-dag`.
- Run the following command from the main directory of your anyway repository:
`docker-compose -f docker-compose.yml -f {RELATIVE_PATH}/docker-compose-override.yaml run anyway-etl waze get-data`
Where `{RELATIVE_PATH}` should be replaced with the relative path to my ETL fork you have cloned in the first step.

### Expected result:

anyway-etl waze get-data command should run

### Actual result:

`ModuleNotFoundError: No module named 'anyway'`

**Comment by OriHoch** [comment]
I editted the issue description to use standard bug report format

**Comment by carmelp16** [comment]
@OriHoch Is there a task that is able to run successfully when you execute it locally using the `docker-compose -f docker-compose.yml -f ../anyway-etl/docker-compose-override.yaml run anyway-etl ` command?
(And it also contains imports of `anyway` module in its implementation?)

**Comment by OriHoch** [comment]
@carmelp16 you still have the same problem as described in the issue description?

**Comment by OriHoch** [comment]
does not reproduce, probably fixed at some point..
