### ISSUE TITLE
CI / CD - production auto update on anyway master commit

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway-etl#20]
It's inconvenient for us today to maintain releases - since some airflow dags use anyway code - and we need to create a release every time anyway code updates.
For now, we prefer production to update every time anyway master updates.

**Comment by OriHoch** [comment]
The airflow dags only depend on anyway model, not on anyway code so I think they only rarely require to be updated

Which dags are you referring to?

**Comment by OriHoch** [comment]
I see there are many changes which I didn't review, so I don't know exactly the current status, but AFAIK the waze and cbs dags depend on anyway model in the following places:

* https://github.com/hasadna/anyway-etl/blob/main/anyway_etl/cbs/import_to_datastore.py#L10
* https://github.com/hasadna/anyway-etl/blob/main/anyway_etl/waze/config.py#L4

**Comment by atalyaalon** [comment]
Thanks.
In that case I believe we can use CI/CD to airflow master - when merging to anyway master.
I see no reason to do it by release - and I assume it's a minor change in the CI/CD pipeline

**Comment by OriHoch** [comment]
yes, it's easy to do, but it increases the risk of breaking the airflow dags, this happened in the past in this issue - https://github.com/hasadna/anyway/issues/1910 - where the anyway code was updated with the error in August 30, but the airflow dags only broke when anyway-etl was released on September 16. Also, if we test anyway-etl releases before deploying we can catch these errors before production, if we deploy immediately to prod we have no chance to catch it before breaking production.

In addition, until now there was never a reason to publish a release for the sole reason of updating the related anyway code (and I don't see any reason to do it in the future). So this change does not make anything easier and doesn't improve anything.

**Comment by atalyaalon** [comment]
I understand. Thank you @OriHoch!
Just to make sure things clear - Any DAG that uses anyway code (rather than anyway model) - for example [these dags](https://github.com/hasadna/anyway-etl/blob/main/airflow_server/dags/news_flash.py) - will run in anyway production (meaning they actually depend on www.github.com/hasadna/anyway CI/CD rather than airflow CI/CD?

**Comment by OriHoch** [comment]
They run the code same as jenkins did on the anyway-main pod, so whatever version is on amyway-main pod is the version that they will run
